import { defineConfig } from "astro/config";
import { readFileSync, existsSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import remarkToc from "remark-toc";
import rehypeSlug from "rehype-slug";
import rehypeAutolinkHeadings from "rehype-autolink-headings";
import { remarkReadingTime } from "./remark-reading-time.mjs";
import { remarkModifiedTime } from "./remark-modified-time.mjs";
import partytown from "@astrojs/partytown";
import sitemap from "@astrojs/sitemap";
import jopSoftwarecookieconsent from "@jop-software/astro-cookieconsent";
import remarkMermaid from "remark-mermaidjs";
import { unified } from "@astrojs/markdown-remark";

import react from "@astrojs/react";

const SITE_URL = "https://etienne.deneuve.xyz";

const __dirname = dirname(fileURLToPath(import.meta.url));
const thinkingRedirectsPath = join(__dirname, "src/data/thinking-redirects.json");
const thinkingRedirects = existsSync(thinkingRedirectsPath)
  ? JSON.parse(readFileSync(thinkingRedirectsPath, "utf8"))
  : { redirects: [] };

const legacyThinkingRedirects = Object.fromEntries(
  (thinkingRedirects.redirects ?? [])
    .filter((entry) => entry.reason?.startsWith("legacy-slug"))
    .map((entry) => [entry.from, entry.to])
);

/** URLs that must not appear in the sitemap (redirects, drafts, internal). */
function isSitemapExcluded(page) {
  const path = page.replace(SITE_URL, "");
  if (path.includes("/draft/") || path.includes("/design-system") || path.includes("/404")) {
    return true;
  }
  // Literal redirect param stubs generated by Astro
  if (path.includes("/:") || path.includes("%3A")) return true;
  // Legacy WordPress date URLs (root + under /thinking/)
  if (/\/\d{4}\/\d{2}\/\d{2}\//.test(path)) return true;
  if (/\/thinking\/\d{4}\//.test(path)) return true;
  // Root-level redirect stubs from [...slug].astro (canonical lives under /thinking/)
  if (/^\/\d{4}-\d{2}-\d{2}-[^/]+\/?$/.test(path)) return true;
  // Configured redirects / old IA
  if (
    path === "/blog" ||
    path.startsWith("/blog/") ||
    path === "/offers" ||
    path.startsWith("/offers/") ||
    path === "/case-studies" ||
    path.startsWith("/case-studies/") ||
    path === "/en/blog" ||
    path.startsWith("/en/blog/") ||
    path === "/en/offers" ||
    path.startsWith("/en/offers/") ||
    path === "/en/case-studies" ||
    path.startsWith("/en/case-studies/")
  ) {
    return true;
  }
  // Explicit legacy thinking redirects map
  for (const from of Object.keys(legacyThinkingRedirects)) {
    const normalizedFrom = from.endsWith("/") ? from : `${from}/`;
    if (path === from || path === normalizedFrom || path.startsWith(normalizedFrom)) {
      return true;
    }
  }
  return false;
}

// https://astro.build/config
export default defineConfig({
  site: SITE_URL,
  base: "",
  redirects: {
    "/blog": "/thinking/",
    "/blog/page/:page": "/thinking/",
    "/offers": "/work/",
    "/case-studies": "/work/case-studies/",
    "/case-studies/:slug": "/work/case-studies/:slug/",
    "/en/blog": "/en/thinking/",
    "/en/offers": "/en/work/",
    "/en/case-studies": "/en/work/case-studies/",
    "/en/case-studies/:slug": "/en/work/case-studies/:slug/",
    ...legacyThinkingRedirects,
  },
  integrations: [
    sitemap({
      filter: (page) => !isSitemapExcluded(page),
    }),
    partytown({
      // Adds dataLayer.push as a forwarding-event.
      config: {
        forward: ["dataLayer.push"],
      },
    }),
    jopSoftwarecookieconsent({
      categories: {
        necessary: {
          enabled: true,
          // this category is enabled by default
          readOnly: true, // this category cannot be disabled
        },
        analytics: {},
      },
      guiOptions: {
        consentModal: {
          layout: "bar inline",
          position: "bottom",
          flipButtons: true,
          equalWeightButtons: true,
        },
        preferencesModal: {
          layout: "box",
          // position: 'left right',
          flipButtons: false,
          equalWeightButtons: true,
        },
      },
      language: {
        default: "fr",
        translations: {
          fr: {
            consentModal: {
              title: "J'utilise quelques cookies",
              description: "Je vous rassure, pas grand chose... mais je vais vous le dire.",
              acceptAllBtn: "Tout accepter",
              acceptNecessaryBtn: "Tout refuser",
              showPreferencesBtn: "Gérer les préférences individuelles",
            },
            preferencesModal: {
              title: "Gérer les préférences des cookies",
              acceptAllBtn: "Tout accepter",
              acceptNecessaryBtn: "Tout refuser",
              savePreferencesBtn: "Accepter la sélection actuelle",
              closeIconLabel: "Fermer la fenêtre modale",
              sections: [
                {
                  title: "Performance et analyse",
                  description:
                    "Ces cookies collectent des informations sur votre utilisation de ce site web. Toutes les données sont anonymisées et ne peuvent pas être utilisées pour vous identifier.",
                  linkedCategory: "analytics",
                },
              ],
            },
          },
          en: {
            consentModal: {
              title: "I use some cookies",
              description: "But, I'll tell you about it...",
              acceptAllBtn: "Accept all",
              acceptNecessaryBtn: "Reject all",
              showPreferencesBtn: "Manage Individual preferences",
            },
            preferencesModal: {
              title: "Manage cookie preferences",
              acceptAllBtn: "Accept all",
              acceptNecessaryBtn: "Reject all",
              savePreferencesBtn: "Accept current selection",
              closeIconLabel: "Close modal",
              sections: [
                {
                  title: "Performance and Analytics",
                  description:
                    "These cookies collect information about how you use our website. All of the data is anonymized and cannot be used to identify you.",
                  linkedCategory: "analytics",
                },
              ],
            },
          },
        },
      },
    }),
    react(),
  ],
  markdown: {
    // Keep remark/rehype plugins on the unified pipeline (Sätteri is default in Astro 7).
    processor: unified({
      remarkPlugins: [remarkToc, remarkReadingTime, remarkModifiedTime, remarkMermaid],
      rehypePlugins: [
        rehypeSlug,
        [
          rehypeAutolinkHeadings,
          {
            behavior: "append",
          },
        ],
      ],
    }),
    shikiConfig: {
      // Choose from Shiki's built-in themes (or add your own)
      // https://github.com/shikijs/shiki/blob/main/docs/themes.md
      theme: "one-dark-pro",
      // Add custom languages
      // Note: Shiki has countless langs built-in, including .astro!
      // https://github.com/shikijs/shiki/blob/main/docs/languages.md
      langs: [],
      // Enable word wrap to prevent horizontal scrolling
      wrap: true,
    },
  },
});
