name: CI

on: [push,pullrequest]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
          # Runs a single command using the runners shell
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3.4.0
        with:
          publish_dir: ./build
          publish_branch: master
          github_token: ${{ secrets.GITHUB_TOKEN }}
